# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
