# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0002_auto_20170512_1446'),
        ('Classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateField(default=datetime.datetime.now)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Cartao')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classe.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.IntegerField(choices=[(1, 'DEBITO'), (2, 'CREDITO')])),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Conta')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.IntegerField(choices=[(1, 'MANHÃ'), (2, 'TARDE'), (3, 'NOITE')], default=2)),
            ],
        ),
        migrations.AddField(
            model_name='consumo',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financeiro.Refeicao'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
    ]
